# Generated by Django 5.2.8 on 2025-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature'), ('portrait', 'Portrait'), ('urban', 'Urban'), ('wildlife', 'Wildlife'), ('abstract', 'Abstract'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photographer',
            field=models.CharField(blank=True, help_text='Name of the photographer', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(help_text='Title of the photograph', max_length=100),
        ),
    ]
